### ISSUE TITLE
Sending Reset Command. No response for command 0x00000006

### ISSUE THREAD

**Issue by csukuangfj** [sparkfun/SparkFun_Edge_BSP#6]
This is **NOT** the same issue as described in #3 

Why is there no response after pressing the `reset` button (with button 14 released) ?

The os
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

$ make bootload
../../../../../tools/apollo3_scripts/create_cust_image_blob.py --bin bin/xxx.bin --load-address 0xC000 --magic-num 0xCB -o bin/main_nonsecure_ota --version 0x0
Header Size =  0x80
original app_size  0x2ba5c ( 178780 )
load_address  0xc000 ( 49152 )
app_size  0x2ba5c ( 178780 )
w0 = 0xcb02badc
Security Value  0x10
w2 =  0x10008080
addrWord =  0xc000
versionKeyWord =  0x0
child0/feature =  0xffffffff
child1 =  0xffffffff
crc =   0x7a65ec24
Writing to file  bin/main_nonsecure_ota.bin
../../../../../tools/apollo3_scripts/create_cust_wireupdate_blob.py --load-address 0x20000 --bin bin/main_nonsecure_ota.bin -i 6 -o bin/main_nonsecure_wire --options 0x1
Header Size =  0x60
app_size  0x2badc ( 178908 )
Writing to file  bin/main_nonsecure_wire.bin
Image from  0x0  to  0x2badc  will be loaded at 0x20000
../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py -b 115200 /dev/cu.wchusbserial1420  -r 1 -f bin/main_nonsecure_wire.bin -i 6
Connecting with Corvette over serial port /dev/cu.wchusbserial1420...
Sending Hello.
Received response for Hello
Received Status
length =  0x58
version =  0x3
Max Storage =  0x4ffa0
Status =  0x2
State =  0x7
AMInfo =
0x1
0xff2da3ff
0x55fff
0x1
0x49f40003
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
0xffffffff
Sending OTA Descriptor =  0xfe000
Sending Update Command.
number of updates needed =  1
Sending block of size  0x2bb3c  from  0x0  to  0x2bb3c
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  8180
Sending Data Packet of length  7224
Sending Reset Command.
No response for command 0x00000006
received bytes  19
['0xb7', '0xa5', '0x61', '0x81', '0x7', '0x0', '0x14', '0x0', '0x6', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0', '0x0']
Traceback (most recent call last):
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 341, in <module>
    main()
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 42, in main
    connect_device(ser)
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 175, in connect_device
    send_ackd_command(resetmsg, ser)
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 194, in send_ackd_command
    response = send_command(command, 20, ser)
  File "../../../../../boards/SparkFun_Edge_BSP/bsp/tools/uart_wired_update_sparkfun.py", line 238, in send_command
    raise NoResponseError
__main__.NoResponseError
make: *** [bootload] Error 1

**Comment by csukuangfj** [comment]
Same error in Ubuntu 16.04.

**Comment by oclyke** [comment]
Hi @csukuangfj, first of all thanks for submitting an issue, we're glad to see engagement from the community. 

I have seen this error before as well, however I can only try to imagine what may be causing the problem because we don't know the finer details of how the baked-in bootloader on the Apollo3 works. The best we can do is to examine the script ```uart_wired_update_sparkfun.py``` (which is the same as the Ambiq provided uart uploader scipt except for a small delay just before initializing communication) to try to back out the necessary functionality. 

Does this prevent you from uploading your code? When I've encountered this problem before I was able to simply press reset manually when prompted by ```Sending Reset Command.``` and found the new firmware running properly.

We are considering the possibility of writing our own bootloader on top of the baked-in bootloader in order to help alleviate several of the problems we've identified. Since we will have control over that process we can make sure the code upload experience is nearly flawless.

Therefore we probably will not investigate this issue much further. If that answered your question please feel free to close this issue.

**Comment by csukuangfj** [comment]
@oclyke 
thanks for the reply. I will close it.
